name: "Continue Vertex AI Test"
version: "1.0"
schema: "1"

models:
  - title: "Gemini 1.5 Flash (Vertex AI)"
    provider: "openai"
    model: "gemini-1.5-flash"
    apiBase: "http://localhost:3000/v1"
    apiKey: "sk-vertex-ai"
    roles: ["chat"]
    
  - title: "Gemini 1.5 Pro (Vertex AI)"
    provider: "openai"
    model: "gemini-1.5-pro"
    apiBase: "http://localhost:3000/v1"
    apiKey: "sk-vertex-ai"
    roles: ["chat"]
    
  - title: "Claude 3.5 Sonnet (Vertex AI)"
    provider: "openai"
    model: "claude-3-5-sonnet-20241022"
    apiBase: "http://localhost:3000/v1"
    apiKey: "sk-vertex-ai"
    roles: ["chat"]

contextProviders:
  - name: "files"
    
rules:
  - "Keep responses concise and helpful"
  - "Use Vertex AI as unified gateway"
  
customCommands:
  - name: "test"
    prompt: "Respond with 'Hello from Vertex AI!'" 